{% set name = "tasklogger" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/scottgigante/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e066b6990045f4d34bf80ec49397fe29a2cc4f583b4479c2d6afcfa3f265416e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - future
    - python

test:
  imports:
    - tasklogger

about:
  home: https://github.com/scottgigante/tasklogger
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: An extension to the core python logging library for logging the beginning and completion of tasks and subtasks

extra:
  recipe-maintainers:
    - bebatut
    - scottgigante
