{% set name = "tasklogger" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scottgigante/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 489ab5172523cba66e9afffe10b5abcfeb46e1bfafa66cafb199c148175b14f5

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - deprecated

test:
  imports:
    - tasklogger

about:
  home: https://github.com/scottgigante/tasklogger
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An extension to the core python logging library for logging the beginning and completion of tasks and subtasks

extra:
  recipe-maintainers:
    - bebatut
    - scottgigante
